### ISSUE TITLE
TS2688 Cannot find type definition file for 'node_modules'.

### ISSUE THREAD

**Issue by Fjaoos** [ui5-community/generator-ui5-ts-app-fcl#5]
Hi,

I used the yo generator to create a TS app but it shows the following error when you execute tsc --noEmit:

error TS2688: Cannot find type definition file for 'node_modules'.
  The file is in the program because:
    Entry point for implicit type library 'node_modules'

The app has been generated with default values only.

I did some research but could not come up with any solution.

**Comment by lemaiwo** [comment]
@petermuessig , do you have any idea?

**Comment by akudev** [comment]
@Fjaoos Can you please try the following change?
In `tsconfig.json` replace:
```ts
        "typeRoots": [
            "./node_modules/@types",
            "./node_modules/@openui5/ts-types-esm"
        ],
```
with
```ts
        "typeRoots": [
            "./node_modules/@types"
        ],
            "types": [
            "@openui5/ts-types-esm"
        ],
```
(or replace @openui5 with @sapui5, if you used SAPUI5 in the generator)

**Comment by wridgeu** [comment]
Hey @akudev 

I've tried it locally as well (did some thinking yday as well) the change you described works for me. I've checked several issues, the ts docs regarding typeroots/types, blogs and what not, the most prominent probably being https://github.com/microsoft/TypeScript/issues/27956.

If it isn't too much or too long to explain, may I ask why it is that this config change is working? I'm trying to make some sense of it for the future. ^^ Appreciate it! 

Before
![image](https://user-images.githubusercontent.com/14982812/179543555-018066a5-fc1e-4275-ba86-f88b741efff3.png)

After
![image](https://user-images.githubusercontent.com/14982812/179543585-6938b0af-d022-48d3-bc26-d5e2bdd8c148.png)

**Comment by Fjaoos** [comment]
Hi @akudev,
that fix works very well. Might be a chapter for the FAQ.
Thank you for your fix but I would also like to know why that works how it does.

Regards
fjaoos

**Comment by akudev** [comment]
@Fjaoos , @wridgeu I'll let you know and document it once I figured out why it works. ;-)
The suggestion came up during the UI5con workshop, so first prio was to apply the change everywhere and inform people how to do it. Second prio (after other things) will be to understand the behavior in detail...

**Comment by akudev** [comment]
@wridgeu @Fjaoos @lemaiwo Ok, it's now understood - albeit a bit lengthy to explain, as several tricky details come together:

A few months back (in 1.100) the UI5 types started coming with a package.json dependency to the jQuery and qUnit types. The goal was to a) free app developers from explicitly requiring them and to b) ensure the version of those types is included which best fits the jQuery/qUnit version actually embedded in UI5.
As result, the jQuery types also end up in `<appfolder>/node_modules` when `@openui5/ts-types-esm` is added as dependency and are picked up by TypeScript. (of course all the same for @sapui5)

Because the `@openui5/ts-types-esm` types are _not_ in the default `@types` package, one has to mention them explicitly in the `tsconfig.json`. We decided for using the "typeRoots" property for that because when using "types" ONLY these types would be available (at least globally) and one would have to explicitly list all types needed for global usage. The second typeRoots entry was for the standard folder:
```ts 
        "typeRoots": [
            "./node_modules/@types",
            "./node_modules/@openui5/ts-types-esm"
        ],
```
This was the recommendation since 1.100.


But this fcl app template and also the original TypeScript Easy-UI5 template used for the UI5con workshop, where the same issue was discussed, had for some reason (probably because it was formerly required) its own dependency to the jQuery types. And [still has](https://github.com/SAP-samples/ui5-typescript-tutorial/blob/main/generator/generators/app/templates/package.json#L26). 
To a *different version* of the jQuery types than the one UI5 has as dependency! How does npm solve this conflict? The app-required jQuery types go right to `<appfolder>/node_modules`, the ones required by the UI5 types go to `<appfolder>/node_modules/@openui5/ts-types-esm/node_modules`!
So suddenly there is a new folder below `ts-types-esm` which did not exist before.

The [official documentation for "typeRoots"](https://www.typescriptlang.org/tsconfig#typeRoots) does not mention it at all, but [an old comment by the TypeScript dev team lead](https://github.com/microsoft/TypeScript/issues/35440#issuecomment-568123091) made me understand that TS expects ALL folders directly below a "typeRoot" to be "types folders" and that each such "types folder" *MUST* have an `index.d.ts` file or a `package.json`. 
The new nested `node_modules` folder, however, has neither as direct content (even though two levels below there is such a types folder for the jQuery types), hence the error message "TS2688 Cannot find type definition file for 'node_modules'" which this issue is about.

**It basically complains that the `node_modules` folder within `@openui5/ts-types-esm` does not contain types although as child of a "typesRoot" folder it should.**

The solution proposed above works because the OpenUI5 types are no longer in the "typesRoot" section, but in the "types" section. TypeScript hence just loads the types and is happy, ignoring the `node_modules` folder below.
```ts
        "typeRoots": [
            "./node_modules/@types"
        ],
        "types": [
            "@openui5/ts-types-esm"
        ],
```
However, there is one drawback: as mentioned before, making `@openui5/ts-types-esm` a "types" entry causes any _other_ types not to be available globally. They ARE still available when the respective module is imported and also available for Quick Fixes, so it is not that dramatic. But you e.g. cannot use the global jQuery object anymore without importing it as module. (well, you can use it at runtime, but TypeScript won't know it) 
The question is whether one _should_ do so, but anyway, the solution is simple: just add it to the "types" section.
```ts
        "typeRoots": [
            "./node_modules/@types"
        ],
        "types": [
            "@openui5/ts-types-esm",
            "jQuery"
        ],
```
And indeed right now it LOOKS LIKE the "typeRoots" entry for the standard types might not be needed at all, so the following *might* also suffice as solution:
```ts
        "types": [
            "@openui5/ts-types-esm",
            "jQuery"
        ],
```

On the other hand we know now what the error message was about and how to avoid it (only require the jQuery types ONCE). When doing so, the original way of pointing to the types continues to work fine:
```ts
        "typeRoots": [
            "./node_modules/@types",
            "./node_modules/@openui5/ts-types-esm"
        ],
```

> One thing to keep in mind: as soon as the jQuery types have gone to the nested `node_modules` folder, they won't move up to the root-level one, even when the app dependency is removed. You have to delete them (possibly also `package-lock.json`) and run `npm i` again.


We haven't made up our mind yet which way to recommend and not fully tested all implications, but at least it is now pretty clear what happens and what the available options are.

**Comment by wridgeu** [comment]
wow @akudev. Thank you _so so so_ much for the detailed explanation. Much appreciated!

> The [official documentation for "typeRoots"](https://www.typescriptlang.org/tsconfig#typeRoots) does not mention it at all, but https://github.com/microsoft/TypeScript/issues/35440#issuecomment-568123091 made me understand that TypeScript expects ALL folders which are direct children of a "typeRoot" to be "types folders" and that each such "types folder" MUST have an index.d.ts file or a package.json.
The new nested node_modules folder, however, has neither as direct content (even though two levels below there is such a types folder for the jQuery types), hence the error message "TS2688 Cannot find type definition file for 'node_modules'" which this issue report is about.

When looking into this myself I've had various "suspicions" regarding the `node_modules` folder within `@openui5/ts-types-esm`.  I'm super happy that I wasn't totally wrong here and of course I was missing quite some context which thanks to you, I now have and understood. One key-aspect (for me) is the explanation from the TS dev team lead, that really helps a lot, great find.

>We haven't made up our mind yet which way to recommend and not fully tested all implications, but at least it is now pretty clear what happens and what the available options are.

I'd say this issue should then be kept open as reference point or until it is either documented somewhere "more central" where it'd make sense or a recommendation can be given?

**Comment by lemaiwo** [comment]
Thank you @akudev ! 

Should we already change the template? Or do we wait for further recommendations from the UI5 team?

**Comment by akudev** [comment]
@wridgeu @lemaiwo We are going back to "typeRoots" for both the default @types folder as well as the UI5 types. And making sure the templates don't have a jQuery types dependency (which they shouldn't have had anymore, anyway). 

[Here](https://sap.github.io/ui5-typescript/known-issues.html) I have added a summary of the issue in a more central place, so from my perspective this issue report could now be tied to the [settings in THIS template](https://github.com/ui5-community/generator-ui5-ts-app-fcl/blob/main/generators/app/templates/package.json#L34) (both jQuery and qUnit) and be closed once the dependencies are removed.

**Comment by akudev** [comment]
This is a sort of never-ending story. With [TypeScript 5.1](https://devblogs.microsoft.com/typescript/announcing-typescript-5-1/#explicit-typeroots-disables-upward-walks-for-node_modules-types) the lookup behavior was changed when `typeRoots` is given. This leads to an error with the setup proposed above.

The current recommendation for tsconfig in TypeScript 5.1 onwards (but also usable in lower versions) is hence *not* to set any `typeRoots`, but instead to set `types` to the respective @openui5/@sapui5 ones plus all other used types. Or in case the standard-named `@types/openui5` is used, not to set either.

**Comment by akudev** [comment]
@prasanthkarukkuvel Well, actually - as mentioned above - the recommendation is not to set `typeRoots`, but instead to explicitly list the used `types` as e.g. done in the Easy UI5 template used [in the tutorial](https://github.com/SAP-samples/ui5-typescript-tutorial/blob/main/exercises/ex1/com.myorg.myapp/tsconfig.json#L12):
```json
"types": ["@openui5/types", "@types/qunit"]
```

Your suggestion, however, is not wrong and will also work, but one might still run into [this problem](https://sap.github.io/ui5-typescript/known-issues.html). The official suggestion, on the other hand, means that one has to remember to add all additional types explicitly. So both ways have their advantages and drawbacks and we also had some discussions what to favor at the moment.

**Comment by wridgeu** [comment]
Hi @akudev, as this might be an ongoing topic (like it already has been now :D), maybe it makes sense to have an ongoing Github "Discussion" opened somewhere or have a `tsconfig` recommendation section (or something like it) added to https://sap.github.io/ui5-typescript/?

**Comment by akudev** [comment]
@wridgeu While the [known issues](https://sap.github.io/ui5-typescript/known-issues.html) already covered this topic, I have added an [FAQ page](https://sap.github.io/ui5-typescript/faq.html) with a section on it.

**Comment by wridgeu** [comment]
Awesome, thank you! Also good to know that there is a known issues section - never noticed 😅

**Comment by BenReim** [comment]
@akudev The issue still exists when using the `sapui5/types` with yarn (v3.4.1) and PnP. 
```
Cannot find type definition file for '@sapui5/types'.
  The file is in the program because:
    Entry point of type library '@sapui5/types' specified in compilerOptions
```

The workaround from the FaQ (not specifying `typesRoot`) does not work here however

**Comment by akudev** [comment]
@BenReim I have mentioned this problem in the second section of the [known issues](https://sap.github.io/ui5-typescript/known-issues.html) document.

**Comment by akudev** [comment]
For reference, another extended write-up of this topic with a bit more explanation than the compact "known issues" section: https://github.com/SAP/ui5-typescript/issues/461#issuecomment-2185831969
